"""Add user_type to user model

Revision ID: 3350dacdc7b6
Revises: 7487f1b506e0
Create Date: 2024-07-12 13:39:56.343444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3350dacdc7b6'
down_revision = '7487f1b506e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
